version: '3.0'

services:
  web:
    build: .
    image: study2895/flask:3.0
    ports:
      - "5000:5000"

  push-to-docker-hub:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HUB_USERNAME=study2895
      - DOCKER_HUB_PASSWORD=dckr_pat_WJTdWjYJSShZk1Q3w5fkGTgMSaI
      - DOCKER_HUB_REPO=study2895/flask
    command: >
      /bin/sh -c '
        docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD" &&
        docker build -t $DOCKER_HUB_REPO:3.0 . &&
        docker tag $DOCKER_HUB_REPO:3.0 $DOCKER_HUB_REPO:latest &&
        docker push $DOCKER_HUB_REPO:3.0 &&
        docker push $DOCKER_HUB_REPO:latest
      '
